services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./client:/var/www/client:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api
        networks:
            - app-network
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/var/www/api
        expose:
            - "9000"
        networks:
            - app-network
    database:
        env_file: ./api/.env
        image: mysql:8
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - .docker/db/data:/var/lib/mysql:rw
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
